#!/usr/bin/env python

'''music server main script.'''

import argparse

import musicserver

__author__ = 'Antonio Serrano Hernandez'
__copyright__ = 'Copyright 2021'
__license__ = 'proprietary'
__version__ = '0.1'
__maintainer__ = 'Antonio Serrano Hernandez'
__email__ = 'toni.serranoh@gmail.com'
__status__ = 'Development'
__script__ = 'music-server'

def parse_args():
    parser = argparse.ArgumentParser(
        description='A server to enqueue songs.', prog=__script__)
    parser.add_argument('-c', '--conf', required=True,
        help='the configuration file for the music server')
    parser.add_argument('-d', '--daemonize', action='store_true',
        help='daemonize this process')
    parser.add_argument('-p', '--pidfile', help='the PID file')
    parser.add_argument('--version', action='version',
        version=f'%(prog)s {__version__}')
    return parser.parse_args()

if __name__ == '__main__':
    args = parse_args()
    app = musicserver.Application(args.conf)
    d = musicserver.utils.daemon.Daemon(app, args.daemonize, args.pidfile)
    with d:
        app.run()

